<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "z3_fal"
 *
 * Auto generated by Extension Builder 2015-02-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'z3 Fal',
	'description' => 'Fal-Frontend with list and search. for now. to be extended!',
	'category' => 'plugin',
	'author' => 'Sven Külpmann',
	'author_email' => 'sven.kuelpmann@lenz-wie-fruehling.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
			'extbase_fal' => '0.0.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);